/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.time.format.DateTimeFormatter;
import user_classes.Connection_provider;
import user_classes.DbOperation;
/**
 *
 * @author hp
 */
public class IngridentOrder extends javax.swing.JFrame {

    /**
     * Creates new form IngridentOrder
     */
    public IngridentOrder() {
        initComponents();
        showIngridents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    ResultSet rs = null, rs1 = null, rs3=null;
   Connection con = null;
   public double amount(){
        try{
        rs3 = DbOperation.getData("select* from ingrident where ingridentID = " + Integer.valueOf(IDTxt.getText()));
        rs3.next();
        String amount1 = rs3.getString("amountLeft");
        double amount2 = Double.parseDouble(amount1);
        return amount2;
        }catch(Exception e){
            return 0;
        }
    }
    int key =0;
    public void amountLeft(){
          try{
            con = Connection_provider.getCon();
            double amountLeft = amount()  - Double.parseDouble(quantitiyTxt.getText());
            PreparedStatement pst = con.prepareStatement("update ingrident set amountLeft = ? where ingridentID = " + Integer.valueOf(IDTxt.getText()));
            pst.setDouble(1, amountLeft);
            int row = pst.executeUpdate();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    public boolean amountLeft2(){
        try{
            con = Connection_provider.getCon();
            double amountLeft = amount()  - Double.parseDouble(quantitiyTxt.getText());
            if(amountLeft >= 0){
                return true;
            }else{
                return false;
            }
        }catch(Exception e){
            return false;
        }
    }
    public void showIngridents(){
           rs = DbOperation.getData("select * from Ingrident");
           itemesTable.setModel(DbUtils.resultSetToTableModel(rs));
           
    }
     
    int orderID;
    public void countId(){
        try{
           rs1 = DbOperation.getData("select max(OrderID) from ingridentOrder");
           rs1.next();
           orderID = rs1.getInt(1)+1;
        }catch(Exception e){
          
        }
    }
        public void showOrders(){
           rs1 = DbOperation.getData("select* from ingridentOrder");
           orderTable.setModel(DbUtils.resultSetToTableModel(rs1));
           
    }
        
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        quantitiyTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemesTable = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        totalLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        todayOrderTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ingrident_ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 123, 149, 42));

        IDTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IDTxt.setForeground(new java.awt.Color(255, 102, 102));
        IDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTxtActionPerformed(evt);
            }
        });
        jPanel1.add(IDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 177, 149, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Price");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 220, 104, 42));

        priceTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        priceTxt.setForeground(new java.awt.Color(255, 102, 102));
        jPanel1.add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 268, 149, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("user name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 123, 104, 42));

        userTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userTxt.setForeground(new java.awt.Color(255, 102, 102));
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        jPanel1.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 177, 139, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Quantitiy");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 226, 104, 36));

        quantitiyTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quantitiyTxt.setForeground(new java.awt.Color(255, 102, 102));
        quantitiyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitiyTxtActionPerformed(evt);
            }
        });
        jPanel1.add(quantitiyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 268, 139, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Order Ingridents");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 23, 320, 42));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ingrident list");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 83, 269, 42));

        itemesTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ingrident_ID", "Ingrident_name", "price", "Amount", "Catagory", "Supplier_ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemesTable.setRowHeight(29);
        itemesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemesTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 598, 216));

        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 51, 102));
        addBtn.setText("Add order");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 317, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("Order history");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, 240, 36));

        orderTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "order_ID", "ingrident_id", "amount_ordered", "manager_id", "total_price", "order_date", "Status", "Delivered_time"
            }
        ));
        orderTable.setRowHeight(29);
        jScrollPane2.setViewportView(orderTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 710, 201));

        totalLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        totalLbl.setForeground(new java.awt.Color(255, 255, 255));
        totalLbl.setText("Total price");
        jPanel1.add(totalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 270, 36));

        todayOrderTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        todayOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "order_Number", "ingrident_id", "amount_ordered", "manager_id", "total_price"
            }
        ));
        todayOrderTable.setRowHeight(29);
        jScrollPane3.setViewportView(todayOrderTable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 566, 201));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("Todays order");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 240, 36));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("Log out");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 0));
        jLabel3.setText("food and drinks");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1347, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTxtActionPerformed

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void quantitiyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitiyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitiyTxtActionPerformed

    private void itemesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemesTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) itemesTable.getModel();
        int myIndex = itemesTable.getSelectedRow();
        key = Integer.parseInt(model.getValueAt(myIndex, 0).toString());
        IDTxt.setText(model.getValueAt(myIndex, 0).toString());
        priceTxt.setText(model.getValueAt(myIndex, 2).toString());
    }//GEN-LAST:event_itemesTableMouseClicked
    double total = 0;
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        ResultSet rs4 = DbOperation.getData("select* from manager where userName =' " + userTxt.getText() + "'");
        if(quantitiyTxt.getText().isEmpty() || userTxt.getText().isEmpty() || IDTxt.getText().isEmpty() || priceTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing information!!!");
        }else{
            double subTotal = Double.valueOf(priceTxt.getText())* Double.valueOf(quantitiyTxt.getText());
            total = total + subTotal;
            try{
                if(amountLeft2()){
                    countId();
                    con = Connection_provider.getCon();
                    PreparedStatement pst = con.prepareStatement("insert into ingridentOrder values(?,?,?,?,?,?,?)");
                    pst.setInt(1, orderID);
                    pst.setString(4, userTxt.getText());
                    pst.setDouble(3, Double.parseDouble(quantitiyTxt.getText()));
                    pst.setInt(2, Integer.parseInt(IDTxt.getText()));
                    pst.setDouble(5, subTotal);
                    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
                    LocalDateTime now = LocalDateTime.now();
                    String dateTimeString = now.format(dtf);
                    pst.setString(6, dateTimeString);
                    pst.setString(7, "Not delivered");
                    int row = pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "order added!!!");
                    con.close();
                    amountLeft();
                    showIngridents();
                    showOrders();
                    totalLbl.setText("Total price = "+total);
                    DefaultTableModel model = (DefaultTableModel) todayOrderTable.getModel();
                    String nextRowId = Integer.toString(model.getRowCount());
                    model.addRow(new Object[] {
                        nextRowId,
                        IDTxt.getText(),
                        quantitiyTxt.getText(),
                        userTxt.getText(),
                        subTotal
                    });
                }else{
                    JOptionPane.showMessageDialog(this, "The amount left is low");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Some wrong information!!!");
            }
        }

    }//GEN-LAST:event_addBtnActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new Items().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngridentOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngridentOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngridentOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngridentOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngridentOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTxt;
    private javax.swing.JButton addBtn;
    private javax.swing.JTable itemesTable;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable orderTable;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField quantitiyTxt;
    private javax.swing.JTable todayOrderTable;
    private javax.swing.JLabel totalLbl;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
