/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.time.format.DateTimeFormatter;
import user_classes.Connection_provider;
import user_classes.DbOperation;
/**
 *
 * @author hp
 */
public class Selling extends javax.swing.JFrame {

    /**
     * Creates new form Selling
     */
    public Selling() {
        initComponents();
        showProducts();
        priceTxt.setEditable(false);
        IDTxt.setEditable(false);
       
        
        
    }
    
    public Selling(String userName){
        initComponents();
        showProducts();
        priceTxt.setEditable(false);
        IDTxt.setEditable(false);
        userTxt.setEditable(false);
        userTxt.setText(userName);
       
    }
    ResultSet rs = null, rs1 = null , rs2 = null, rs3 = null;
   Connection con = null;
    @SuppressWarnings("unchecked")
    public int amount(){
        try{
        rs3 = DbOperation.getData("select* from item where itemID = " + Integer.valueOf(IDTxt.getText()));
        rs3.next();
        String amount1 = rs3.getString("amountLeft");
        int amount2 = Integer.parseInt(amount1);
        return amount2;
        }catch(Exception e){
            return 0;
        }
    }
    int key =0;
    public void amountLeft(){
          try{
            con = Connection_provider.getCon();
            int amountLeft = amount()  - Integer.parseInt(quantitiyTxt.getText());
            PreparedStatement pst = con.prepareStatement("update item set amountLeft = ? where itemID = " + Integer.valueOf(IDTxt.getText()));
            pst.setInt(1, amountLeft);
            int row = pst.executeUpdate();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    public boolean amountLeft2(){
        try{
            con = Connection_provider.getCon();
            int amountLeft = amount()  - Integer.parseInt(quantitiyTxt.getText());
            if(amountLeft >= 0){
                return true;
            }else{
                return false;
            }
        }catch(Exception e){
            return false;
        }
    }
    int foodID;
    public void countId2(){
        try{
           rs1 = DbOperation.getData("select max(itemID) from item");
           rs1.next();
           foodID = rs1.getInt(1)+1;
        }catch(Exception e){
          
        }
    }
    public void showProducts(){
           rs = DbOperation.getData("select* from item");
           showItemTable.setModel(DbUtils.resultSetToTableModel(rs));
           
    }
    public void showOrders(){
           rs1 = DbOperation.getData("select* from orders where customerId = '" + userTxt.getText() + "'");
           orderTable.setModel(DbUtils.resultSetToTableModel(rs1));
           
    }
    int orderID;
    public void countId(){
        try{
           rs2 = DbOperation.getData("select max(orderID) from orders");
           rs2.next();
           orderID = rs2.getInt(1)+1;
        }catch(Exception e){
          
        }
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        IDTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showItemTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        quantitiyTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        todayOrderTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("sell products");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 17, 269, 42));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Price");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 188, 104, 42));

        priceTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        priceTxt.setForeground(new java.awt.Color(255, 102, 102));
        jPanel2.add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 236, 149, -1));

        IDTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IDTxt.setForeground(new java.awt.Color(255, 102, 102));
        IDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTxtActionPerformed(evt);
            }
        });
        jPanel2.add(IDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 145, 149, -1));

        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 51, 102));
        addBtn.setText("Add order");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 286, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("food or drink ID");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 91, 149, 42));

        showItemTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "food_ID", "food_name", "Description", "Price", "amount_left", "managerID"
            }
        ));
        showItemTable.setRowHeight(29);
        showItemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showItemTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(showItemTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 119, 560, 219));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("user name");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 91, 104, 42));

        userTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userTxt.setForeground(new java.awt.Color(255, 102, 102));
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        jPanel2.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 145, 139, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("your todays order");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 330, 240, 36));

        quantitiyTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quantitiyTxt.setForeground(new java.awt.Color(255, 102, 102));
        quantitiyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitiyTxtActionPerformed(evt);
            }
        });
        jPanel2.add(quantitiyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 236, 139, -1));

        orderTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "order_ID", "amount_orderd", "customer_id", "ordered_food_id", "Total", "Order Date", "status"
            }
        ));
        orderTable.setRowHeight(29);
        jScrollPane2.setViewportView(orderTable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 650, 201));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("food and drink items");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 65, 290, 42));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Quantitiy");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 201, 104, 36));

        todayOrderTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        todayOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "order_Number", "amount_orderd", "customer_id", "ordered_food_id", "Sub_total"
            }
        ));
        todayOrderTable.setRowHeight(29);
        jScrollPane3.setViewportView(todayOrderTable);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 372, 479, 201));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 255, 255));
        jLabel15.setText("your order history");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 350, 290, 36));

        totalLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        totalLbl.setForeground(new java.awt.Color(255, 255, 255));
        totalLbl.setText("Total price");
        jPanel2.add(totalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 270, 36));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("Log out");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(485, 485, 485)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    private void IDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTxtActionPerformed

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void quantitiyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitiyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitiyTxtActionPerformed
    double total = 0;
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        if(quantitiyTxt.getText().isEmpty() || userTxt.getText().isEmpty() || IDTxt.getText().isEmpty() || priceTxt.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "Missing information!!!");
       }else{
           double subTotal = Double.valueOf(priceTxt.getText())* Integer.valueOf(quantitiyTxt.getText());
           total = total + subTotal;
           try{
           if(amountLeft2()){
           countId();
           con = Connection_provider.getCon();
           PreparedStatement pst = con.prepareStatement("insert into orders values(?,?,?,?,?,?,?)");
           pst.setInt(1, orderID);
           pst.setString(3, userTxt.getText());
           pst.setInt(2, Integer.parseInt(quantitiyTxt.getText()));
           pst.setInt(4, Integer.parseInt(IDTxt.getText()));
           pst.setDouble(5, subTotal);
           DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
           LocalDateTime now = LocalDateTime.now();
           String dateTimeString = now.format(dtf);
           pst.setString(6, dateTimeString);
           pst.setString(7, "Not delivered");
           int row = pst.executeUpdate();
           JOptionPane.showMessageDialog(this, "order added!!!");
           con.close();
           amountLeft();
           showProducts();
           showOrders();
           countId();
           totalLbl.setText("Total price = "+total);
           DefaultTableModel model = (DefaultTableModel) todayOrderTable.getModel();
        String nextRowId = Integer.toString(model.getRowCount());
        model.addRow(new Object[] {
            nextRowId,
            quantitiyTxt.getText(),
            userTxt.getText(),
            IDTxt.getText(),
            subTotal
        });
        
           }else{
              JOptionPane.showMessageDialog(this, "The amount left is low"); 
           }
           }catch(Exception e){
               JOptionPane.showMessageDialog(this, e);
           }
       }
 
    }//GEN-LAST:event_addBtnActionPerformed
 
    private void showItemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showItemTableMouseClicked
       DefaultTableModel model = (DefaultTableModel) showItemTable.getModel();
        int myIndex = showItemTable.getSelectedRow();
        key = Integer.parseInt(model.getValueAt(myIndex, 0).toString());
        IDTxt.setText(model.getValueAt(myIndex, 0).toString());
        priceTxt.setText(model.getValueAt(myIndex, 4).toString());
    }//GEN-LAST:event_showItemTableMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTxt;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable orderTable;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField quantitiyTxt;
    private javax.swing.JTable showItemTable;
    private javax.swing.JTable todayOrderTable;
    private javax.swing.JLabel totalLbl;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
